name: Build & Apply KServe manifests in KinD
on:
  pull_request:
    paths:
      - contrib/kserve/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Install KinD
      run: ./tests/gh-actions/install_kind.sh

    - name: Create KinD Cluster
      run: kind create cluster --config tests/gh-actions/kind-cluster-1-22.yaml

    - name: Install kustomize
      run: ./tests/gh-actions/install_kustomize.sh

    - name: Install Istio
      run: ./tests/gh-actions/install_istio.sh

    - name: Install cert-manager
      run: ./tests/gh-actions/install_cert_manager.sh

    - name: Build & Apply manifests
      run: ./tests/gh-actions/install_kserve.sh

    - name: Create kserve experiment
      run: |
        sleep 60
        kustomize build common/knative/knative-serving/overlays/gateways | kubectl apply -f -
        kustomize build common/knative/knative-eventing/base | kubectl apply -f -
        kustomize build common/istio-1-14/kubeflow-istio-resources/base | kubectl apply -f -
        kubectl apply -f tests/gh-actions/kf-objects/kserve_test.yaml
        kubectl wait --for=condition=ready inferenceservices.serving.kserve.io --all-namespaces --all --timeout 300s
